name: Production Terraform

# Triggers on:
# - Any change to main branch (PR or push)
# - Excludes global-only modules that shouldn't trigger environment deployments
# - Manual trigger via workflow_dispatch
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'environments/global/**'
      - 'modules/oidc/**'
      - 'modules/logging/**'
      - 'modules/waf/**'
      - 'modules/secrets/**'
  push:
    branches: [main]
    paths-ignore:
      - 'environments/global/**'
      - 'modules/oidc/**'
      - 'modules/logging/**'
      - 'modules/waf/**'
      - 'modules/secrets/**'
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild infrastructure and containers'
        required: false
        default: false
        type: boolean
      rebuild_containers_only:
        description: 'Rebuild containers only (skip infrastructure)'
        required: false
        default: false
        type: boolean
      branch:
        description: 'Branch to use for deployment'
        required: false
        default: 'main'
        type: string

env:
  TF_VERSION: "1.12.0"
  AWS_REGION: "us-east-2"
  ENVIRONMENT: "production"
  WORKSPACE: "production"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch || 'main' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Clear AWS Credentials Cache
        run: |
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
          unset AWS_DEFAULT_REGION
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config
          echo "Cleared all AWS credentials cache"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123324351829:role/github-actions-global
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: production-plan-${{ github.run_id }}-${{ github.run_number }}

      - name: Terraform Init
        working-directory: environments/terraform
        run: terraform init

      - name: Select Production Workspace
        working-directory: environments/terraform
        run: |
          # Create workspace if it doesn't exist
          terraform workspace new ${{ env.WORKSPACE }} || terraform workspace select ${{ env.WORKSPACE }}

      - name: Terraform Plan
        working-directory: environments/terraform
        run: |
          terraform plan \
            -var-file=${{ env.WORKSPACE }}.tfvars \
            -out=tfplan
        continue-on-error: true

      - name: Comment Plan
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            
            let comment = `## Terraform Plan for Production Environment
            
            **Environment**: Production
            **Workspace**: ${{ env.WORKSPACE }}
            **Branch**: main
            **Triggered by**: PR #${{ github.event.number }}`;
            
            try {
              // Use terraform show to convert binary plan to readable text
              const plan = execSync('cd environments/terraform && terraform show tfplan', { encoding: 'utf8' });
              
              // Strip ANSI color codes for GitHub comment readability
              const cleanPlan = plan.replace(/\x1b\[[0-9;]*m/g, '');
              
              comment += `
              
              <details><summary>Click to expand plan</summary>
              
              \`\`\`hcl
              ${cleanPlan}
              \`\`\`
              
              </details>`;
            } catch (error) {
              comment += `
              
              ❌ **Plan Failed**
              
              The Terraform plan step failed. Check the workflow logs for details.
              
              Error: ${error.message}`;
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.force_rebuild == 'true' || github.event.inputs.branch != ''))
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch || 'main' }}

      - name: Debug Branch and Files
        run: |
          echo "## 🔍 DEBUG INFORMATION" >> $GITHUB_STEP_SUMMARY
          echo "**Current Branch:** $(git branch --show-current)" >> $GITHUB_STEP_SUMMARY
          echo "**Git Head:** $(git rev-parse HEAD)" >> $GITHUB_STEP_SUMMARY
          echo "**Git Status:**" >> $GITHUB_STEP_SUMMARY
          git status >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Terraform Directory Contents:**" >> $GITHUB_STEP_SUMMARY
          ls -la environments/terraform/ >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Production Variables (if exists):**" >> $GITHUB_STEP_SUMMARY
          if [ -f "environments/terraform/production.tfvars" ]; then
            cat environments/terraform/production.tfvars >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ production.tfvars file NOT FOUND!" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Clear AWS Credentials Cache
        run: |
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
          unset AWS_DEFAULT_REGION
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config
          echo "Cleared all AWS credentials cache"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123324351829:role/github-actions-global
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: production-apply-${{ github.run_id }}-${{ github.run_number }}

      - name: Terraform Init
        working-directory: environments/terraform
        run: terraform init

      - name: Select Production Workspace
        working-directory: environments/terraform
        run: |
          # Create workspace if it doesn't exist
          terraform workspace new ${{ env.WORKSPACE }} || terraform workspace select ${{ env.WORKSPACE }}

      - name: Terraform Apply
        working-directory: environments/terraform
        run: |
          terraform apply \
            -var-file=${{ env.WORKSPACE }}.tfvars \
            -auto-approve

      - name: Get Outputs
        working-directory: environments/terraform
        run: |
          echo "## Production Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "**Environment**: Production" >> $GITHUB_STEP_SUMMARY
          echo "**Workspace**: ${{ env.WORKSPACE }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch**: main" >> $GITHUB_STEP_SUMMARY
          echo "**Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Infrastructure Outputs:" >> $GITHUB_STEP_SUMMARY
          terraform output >> $GITHUB_STEP_SUMMARY

      - name: Build and Push Docker Image
        if: success()
        run: |
          echo "## 🐳 Building and Pushing Docker Image" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Get ECR repository URL from Terraform output
          ECR_REPO=$(cd environments/terraform && terraform output -raw ecr_repository_url 2>/dev/null || echo "")
          
          if [ -z "$ECR_REPO" ]; then
            echo "❌ ECR repository not found. ECS may not be enabled." >> $GITHUB_STEP_SUMMARY
            echo "Skipping Docker build and push." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi
          
          echo "**ECR Repository:** $ECR_REPO" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Login to ECR
          echo "🔐 Logging in to ECR..."
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REPO
          
          # Build Docker image
          echo "🔨 Building Docker image..."
          docker build -t flask-app:latest app/
          
          # Tag for ECR
          echo "🏷️ Tagging image for ECR..."
          docker tag flask-app:latest $ECR_REPO:latest
          
          # Push to ECR
          echo "📤 Pushing image to ECR..."
          docker push $ECR_REPO:latest
          
          echo "✅ Docker image built and pushed successfully" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** $ECR_REPO:latest" >> $GITHUB_STEP_SUMMARY

      - name: Deploy to ECS
        if: success()
        working-directory: environments/terraform
        run: |
          echo "## 🚀 Deploying to ECS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Get ECS service information
          CLUSTER_NAME=$(terraform output -raw ecs_cluster_name 2>/dev/null || echo "")
          BLUE_SERVICE=$(terraform output -raw blue_ecs_service_name 2>/dev/null || echo "")
          
          if [ -z "$CLUSTER_NAME" ] || [ -z "$BLUE_SERVICE" ]; then
            echo "❌ ECS services not found. ECS may not be enabled." >> $GITHUB_STEP_SUMMARY
            echo "Skipping ECS deployment." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi
          
          echo "**ECS Cluster:** $CLUSTER_NAME" >> $GITHUB_STEP_SUMMARY
          echo "**Blue Service:** $BLUE_SERVICE" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Deploy to blue service
          echo "🔄 Deploying to blue service..."
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $BLUE_SERVICE \
            --force-new-deployment \
            --region ${{ env.AWS_REGION }}
          
          echo "✅ ECS deployment initiated" >> $GITHUB_STEP_SUMMARY
          echo "**Service:** $BLUE_SERVICE" >> $GITHUB_STEP_SUMMARY

      - name: Quick Infrastructure Validation
        working-directory: environments/terraform
        run: |
          echo "## 🚀 Quick Infrastructure Validation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Get ALB DNS name
          ALB_DNS=$(terraform output -raw alb_dns_name)
          ALB_URL=$(terraform output -raw application_url)
          
          echo "**Load Balancer DNS:** $ALB_DNS" >> $GITHUB_STEP_SUMMARY
          echo "**Application URL:** $ALB_URL" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Test ALB health
          echo "🏥 Testing ALB health..."
          for i in {1..10}; do
            if curl -f -s "$ALB_URL/health/simple" > /dev/null; then
              echo "✅ ALB is healthy and responding" >> $GITHUB_STEP_SUMMARY
              break
            else
              echo "⏳ Attempt $i: ALB not ready yet, waiting..." >> $GITHUB_STEP_SUMMARY
              sleep 30
            fi
          done
          
          if [ $i -eq 10 ]; then
            echo "⚠️ ALB health check timed out after 5 minutes" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Bootstrap Database
        if: success()
        working-directory: environments/terraform
        run: |
          echo "## 🗄️ Bootstrap Database" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Check if bootstrap script exists
          if [ ! -f "ecs-database-bootstrap.sh" ]; then
            echo "❌ Bootstrap script not found" >> $GITHUB_STEP_SUMMARY
            exit 0
          fi
          
          # Make script executable
          chmod +x ecs-database-bootstrap.sh
          
          # Run bootstrap
          echo "🔄 Running database bootstrap..."
          if ./ecs-database-bootstrap.sh ${{ env.WORKSPACE }}; then
            echo "✅ Database bootstrap completed successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Database bootstrap failed or skipped" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Final Summary
        run: |
          echo "## 🎉 Production Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Environment**: Production" >> $GITHUB_STEP_SUMMARY
          echo "**Workspace**: ${{ env.WORKSPACE }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch**: main" >> $GITHUB_STEP_SUMMARY
          echo "**Status**: ✅ Deployed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps:" >> $GITHUB_STEP_SUMMARY
          echo "1. Test the application at the ALB URL above" >> $GITHUB_STEP_SUMMARY
          echo "2. Monitor logs in CloudWatch" >> $GITHUB_STEP_SUMMARY
          echo "3. Verify all production systems are operational" >> $GITHUB_STEP_SUMMARY 